org: sergiycheck

service: todo-dynamo-db

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: handler.create
    events:
      - httpApi:
          path: /todos
          method: post

  list:
    handler: handler.list
    events:
      - httpApi:
          path: /todos
          method: get

  get:
    handler: handler.get
    events:
      - httpApi:
          path: /todos/{id}
          method: get

  update:
    handler: handler.update
    events:
      - httpApi:
          path: /todos/{id}
          method: put

resources:
  Resources:
    TodosDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
